seml:
  executable: /path/to/cert.py
  conda_environment: localized_smoothing_images
  project_root_dir: /path/to/localized_smoothing/  # Not the localized_smoothing folder that contains the src files, but one level up
  output_dir: /path/to/localized_smoothing/slurm_out
  name: cert

slurm:
  experiments_per_job: 1
  sbatch_options:
    gres: gpu:1       # num GPUs
    mem: 120G          # memory
    cpus-per-task: 15  # num cores
    time: 4-00:00     # max time, D-HH:MM
    #partition: gpu_large
    #exclude: gpu[15,17,20]

fixed:

  cert_dir: /your/path/to/localized_smoothing_results/cert_cityscapes

  dataset:
    dataset_name: cityscapes
    data_folder: '/nfs/shared/cityscapes/'
    scaling: 0.5
    image_interpolation_method: area
    target_interpolation_method: nearest
    train_set: train
    val_set: val

  padding_params:
    pad_height_divisor: 32
    pad_width_divisor: 32

  sample_params:
    batch_size: 128
    n_samples_pred: 512
    n_samples_cert: 6400

  distribution_params:
    grid_shape: [4, 6]
    metric: l_0
    interpolate_variance: False

  certification_params:
    n_images: 100
    budget_min: 0
    budget_max: 4
    budget_steps: 161
    n_max_rad_bins: 2048
    n_thresholds: 1000
    alpha: 0.01
    eps: None
    binary_search_depth: 16
    naive_certs: ['argmax_bonferroni', 'argmax_holm']
    base_certs: ['argmax_bonferroni', 'argmax_holm']

  train_loading:
    collection: train_images_cityscapes
    exp_id: None
    load_best_iou: True
    find_std_min: True
    restrictions:
      model.model_type: deeplabv3
      transformations.smoothing_params.p: 1

std_min_0_1:
  fixed:
    distribution_params.std_min: 0.1
  grid:
    distribution_params.std_max:
      type: choice
      options:
        - 0.15
        - 0.11
        - 0.19


std_min_0_2:
  fixed:
    distribution_params.std_min: 0.2
  grid:
    distribution_params.std_max:
      type: choice
      options:
        - 0.25
        - 1.1
        - 1.5
        - 0.9


std_min_0_3:
  fixed:
    distribution_params.std_min: 0.3
  grid:
    distribution_params.std_max:
      type: choice
      options:
        - 2.2
        - 5
        - 3
        - 1.8
        - 1.6


std_min_0_05:
  fixed:
    distribution_params.std_min: 0.05
  grid:
    distribution_params.std_max:
      type: choice
      options:
        - 0.06


std_min_0_06:
  fixed:
    distribution_params.std_min: 0.06
  grid:
    distribution_params.std_max:
      type: choice
      options:
        - 0.07


std_min_0_08:
  fixed:
    distribution_params.std_min: 0.08
  grid:
    distribution_params.std_max:
      type: choice
      options:
        - 0.09

std_min_0_09:
  fixed:
    distribution_params.std_min: 0.09
  grid:
    distribution_params.std_max:
      type: choice
      options:
        - 0.1


std_min_0_12:
  fixed:
    distribution_params.std_min: 0.12
  grid:
    distribution_params.std_max:
      type: choice
      options:
        - 0.2
  

std_min_0_13:
  fixed:
    distribution_params.std_min: 0.13
  grid:
    distribution_params.std_max:
      type: choice
      options:
        - 0.14


std_min_0_15:
  fixed:
    distribution_params.std_min: 0.15
  grid:
    distribution_params.std_max:
      type: choice
      options:
        - 0.16


std_min_0_18:
  fixed:
    distribution_params.std_min: 0.18
  grid:
    distribution_params.std_max:
      type: choice
      options:
        - 0.2
        - 0.25
        - 0.3
        - 2.0

std_min_0_19:
  fixed:
    distribution_params.std_min: 0.19
  grid:
    distribution_params.std_max:
      type: choice
      options:
        - 0.2

std_min_0_23:
  fixed:
    distribution_params.std_min: 0.23
  grid:
    distribution_params.std_max:
      type: choice
      options:
        - 0.3

std_min_0_25:
  fixed:
    distribution_params.std_min: 0.25
  grid:
    distribution_params.std_max:
      type: choice
      options:
        - 0.3
