seml:
  executable: /path/to/train.py
  conda_environment: localized_smoothing_images
  project_root_dir: /path/to/localized_smoothing/  # Not the localized_smoothing folder that contains the src files, but one level up
  output_dir: /path/to/logs/slurm_out/train
  name: train

slurm:
  experiments_per_job: 1
  sbatch_options:
    gres: gpu:1       # num GPUs
    mem: 32G          # memory
    cpus-per-task: 6  # num cores
    time: 4-00:00     # max time, D-HH:MM
    # partition: gpu_large
    #exclude: gpu18,gpu19,mdsi-gpu01,mdsi-gpu02

fixed:

  seed: 0
  save_dir: /your/path/to/localized_smoothing_results/images/train_pascal_masked

  dataset:
    dataset_name: pascal
    data_folder: /your/path/to/data  # Path that contains "pascal_voc"
    scaling: 0.5
    image_interpolation_method: area
    target_interpolation_method: nearest

  model:
    model_type: unet
    model_params.encoder_name: resnet18
    model_params.encoder_weights: imagenet

  training_params:
    num_epochs: 300
    lr: 0.001
    batch_size: 128
    max_batch_size: 128
    train_encoder: False
    epochs_val: 8
    stitch_smooth_predictions: True
    accumulate_gradients: True

  transformations:
    ###### Image Space
    random_brightness_params:
      p: 0.0
    random_contrast_params:
      p: 0.0
    blur_params:
      p: 0.0
      blur_limit: 3

    ###### Geometric
    flip_horizontally: True

    shift_scale_rotate_params:
      shift_limit: 0.0
      scale_limit: [0, 1]
      rotate_limit: 0
      p: 0.5
    ###### Padding / Cropping
    padding_params_train:
      border_mode: 0
    padding_params_val:
      border_mode: 0
    random_cropping_params:
      height: 160
      width: 256

3-5-masked:
  fixed:
    transformations.smoothing_params:
      p: 1
      localized: True
      localized_params:
        mask_value: 255
        label_mask_distance: None
        distribution_params:
          grid_shape: [3, 5]
          metric: l_0
          interpolate_variance: False
          mask_distance: 1
          max_std_at_boundary: False
  grid:
    transformations.smoothing_params.localized_params.distribution_params.std_min:
      type: choice
      options:
        - 0.01
        - 0.02
        - 0.03
        - 0.04
        - 0.05
        - 0.06
        - 0.07
        - 0.08
        - 0.09
        - 0.1
        - 0.12
        - 0.15
        - 0.17
        - 0.2
        - 0.22
        - 0.25
        - 0.27
        - 0.3
        - 0.32
        - 0.35
        - 0.37
        - 0.4
        - 0.45
        - 0.5
      zip_id: std
    transformations.smoothing_params.localized_params.distribution_params.std_max:
      type: choice
      options:
        - 0.01
        - 0.02
        - 0.03
        - 0.04
        - 0.05
        - 0.06
        - 0.07
        - 0.08
        - 0.09
        - 0.1
        - 0.12
        - 0.15
        - 0.17
        - 0.2
        - 0.22
        - 0.25
        - 0.27
        - 0.3
        - 0.32
        - 0.35
        - 0.37
        - 0.4
        - 0.45
        - 0.5
      zip_id: std
    transformations.smoothing_params.distribution_params.std:
      type: choice
      options:
        - 0.01
        - 0.02
        - 0.03
        - 0.04
        - 0.05
        - 0.06
        - 0.07
        - 0.08
        - 0.09
        - 0.1
        - 0.12
        - 0.15
        - 0.17
        - 0.2
        - 0.22
        - 0.25
        - 0.27
        - 0.3
        - 0.32
        - 0.35
        - 0.37
        - 0.4
        - 0.45
        - 0.5
      zip_id: std


2-2-masked:
  fixed:
    transformations.smoothing_params:
      p: 1
      localized: True
      localized_params:
        mask_value: 255
        label_mask_distance: None
        distribution_params:
          grid_shape: [2, 2]
          metric: l_0
          interpolate_variance: False
          mask_distance: 1
          max_std_at_boundary: False
  grid:
    transformations.smoothing_params.localized_params.distribution_params.std_min:
      type: choice
      options:
        - 0.01
        - 0.02
        - 0.03
        - 0.04
        - 0.05
        - 0.06
        - 0.07
        - 0.08
        - 0.09
        - 0.10
        - 0.11
        - 0.12
        - 0.13
        - 0.14
        - 0.15
        - 0.16
        - 0.17
        - 0.18
        - 0.19
        - 0.20
        - 0.21
        - 0.22
        - 0.23
        - 0.24
        - 0.25
        - 0.26
        - 0.27
        - 0.28
        - 0.29
        - 0.30
        - 0.31
        - 0.32
        - 0.33
        - 0.34
        - 0.35
        - 0.36
        - 0.37
        - 0.38
        - 0.39
        - 0.40
        - 0.41
        - 0.42
        - 0.43
        - 0.44
        - 0.45
        - 0.46
        - 0.47
        - 0.48
        - 0.49
        - 0.50
      zip_id: std
    transformations.smoothing_params.localized_params.distribution_params.std_max:
      type: choice
      options:
        - 0.01
        - 0.02
        - 0.03
        - 0.04
        - 0.05
        - 0.06
        - 0.07
        - 0.08
        - 0.09
        - 0.10
        - 0.11
        - 0.12
        - 0.13
        - 0.14
        - 0.15
        - 0.16
        - 0.17
        - 0.18
        - 0.19
        - 0.20
        - 0.21
        - 0.22
        - 0.23
        - 0.24
        - 0.25
        - 0.26
        - 0.27
        - 0.28
        - 0.29
        - 0.30
        - 0.31
        - 0.32
        - 0.33
        - 0.34
        - 0.35
        - 0.36
        - 0.37
        - 0.38
        - 0.39
        - 0.40
        - 0.41
        - 0.42
        - 0.43
        - 0.44
        - 0.45
        - 0.46
        - 0.47
        - 0.48
        - 0.49
        - 0.50
      zip_id: std
    transformations.smoothing_params.distribution_params.std:
      type: choice
      options:
        - 0.01
        - 0.02
        - 0.03
        - 0.04
        - 0.05
        - 0.06
        - 0.07
        - 0.08
        - 0.09
        - 0.10
        - 0.11
        - 0.12
        - 0.13
        - 0.14
        - 0.15
        - 0.16
        - 0.17
        - 0.18
        - 0.19
        - 0.20
        - 0.21
        - 0.22
        - 0.23
        - 0.24
        - 0.25
        - 0.26
        - 0.27
        - 0.28
        - 0.29
        - 0.30
        - 0.31
        - 0.32
        - 0.33
        - 0.34
        - 0.35
        - 0.36
        - 0.37
        - 0.38
        - 0.39
        - 0.40
        - 0.41
        - 0.42
        - 0.43
        - 0.44
        - 0.45
        - 0.46
        - 0.47
        - 0.48
        - 0.49
        - 0.50
      zip_id: std



