seml:
  executable: /nfs/homedirs/wollschl/staff/localized_smoothing/seml/scripts/graph/cert.py
  conda_environment: localized-smoothing
  project_root_dir: /nfs/homedirs/wollschl/staff/localized_smoothing/
  output_dir: /nfs/homedirs/wollschl/staff/localized_smoothing/experiments/slurm_out/cert
  name: certify_small

slurm:
  experiments_per_job: 1
  sbatch_options:
    gres: gpu:1       # num GPUs
    mem: 32G          # memory
    cpus-per-task: 6  # num cores
    time: 5-00:00     # max time, D-HH:MM

fixed:
  experiment_name: 'certify_small'
  certify_test: False
  dataset_name: 'cora_ml'

  budget_a: 20
  budget_d: 20
  
  n_clusters: 14
  batch_size: 50
  n_samples_eval: 100_0
  n_samples_pre_eval: 1000

  min_p: 0.0075
  min_m: 0.5

  cluster_args:
    affinity: 'nearest_neighbors'

  model_data:
    name: 'GCN'
    pretrained_name: 'gcn_pretrained_0.5_0.0075'
    model_params:
      n_hidden: 64
      p_dropout: 0.5

grid:
  max_p: 
    type: choice
    options: 
      - 0.01
  max_m:
    type: choice
    options:
      - 0.6