seml:
  executable: /nfs/homedirs/wollschl/staff/localized_smoothing/seml/scripts/graph/cert.py
  conda_environment: localized-smoothing-cuda11
  project_root_dir: /nfs/homedirs/wollschl/staff/localized_smoothing/
  output_dir: /nfs/homedirs/wollschl/staff/localized_smoothing/experiments/slurm_out/cert
  name: certify

slurm:
  experiments_per_job: 1
  sbatch_options:
    gres: gpu:1       # num GPUs
    mem: 64_n G          # memory
    cpus-per-task: 16  # num cores
    time: 2-00:00     # max time, D-HH:MM
    partition: gpu_cuda11

fixed:
  experiment_name: 'certify'
  certify_test: False
  dataset_name: 'cora_ml'

  budget_a: 50
  budget_d: 50
  
  n_clusters: 5
  batch_size: 50
  n_samples_eval: 100_000
  n_samples_pre_eval: 100

  clustering_type: 'metis'
  cluster_args:
    affinity: 'nearest_neighbors'

  model_data:
    name: 'APPNP'
    model_params:
      n_hidden: 64
      p_dropout: 0.5
      k_hops: 10
      alpha: 0.15


pp_min_0075_pm_min_065:
  fixed:
    min_p: 0.0075
    min_m: 0.65
    max_m: 0.95
    model_data.pretrained_name: cora_ml/APPNP/pp_min_0.0075_pm_min_0.65

  grid:
    max_p:
      type: choice
      options:
        - 0.01
        - 0.025
        - 0.05
