seml:
  executable: /nfs/homedirs/wollschl/staff/localized_smoothing/seml/scripts/graph/cert.py
  conda_environment: localized-smoothing
  project_root_dir: /nfs/homedirs/wollschl/staff/localized_smoothing/
  output_dir: /nfs/homedirs/wollschl/staff/localized_smoothing/experiments/slurm_out/cert
  name: test-data-saving

slurm:
  experiments_per_job: 1
  sbatch_options:
    gres: gpu:1       # num GPUs
    mem: 32G          # memory
    cpus-per-task: 6  # num cores
    time: 1-00:00     # max time, D-HH:MM

fixed:
  experiment_name: 'certify'
  certify_test: False
  dataset_name: 'cora_ml'

  budget_a: 20
  budget_d: 20
  
  n_clusters: 14
  n_samples_eval: 100
  n_samples_pre_eval: 100

  min_p: 0.0075
  max_p: 0.08
  min_m: 0.5
  max_m: 0.8

  cluster_args:
    affinity: 'nearest_neighbors'
    
  model_data:
    name: 'GCN'
    pretrained_name: 'gcn_pretrained_0.5_0.0075'
    model_params:
      n_hidden: 64
      p_dropout: 0.5