seml:
  executable: /nfs/homedirs/wollschl/staff/localized_smoothing/seml/scripts/graph/cert.py
  conda_environment: localized-smoothing
  project_root_dir: /nfs/homedirs/wollschl/staff/localized_smoothing/
  output_dir: /nfs/homedirs/wollschl/staff/localized_smoothing/experiments/slurm_out/cert
  name: certify_deletion_gcn

slurm:
  experiments_per_job: 1
  sbatch_options:
    gres: gpu:1       # num GPUs
    mem: 32G          # memory
    cpus-per-task: 6  # num cores
    time: 0-05:00     # max time, D-HH:MM
    partition: gpu_cuda11

fixed:
  experiment_name: 'certify_deletion_gcn'
  certify_test: False
  dataset_name: 'cora_ml'

  budget_a: 30
  budget_d: 30
  
  n_clusters: 5
  batch_size: 50
  n_samples_eval: 100_0
  n_samples_pre_eval: 100

  clustering_type: 'metis'
  cluster_args:
    affinity: 'precomputed'

  model_data:
    name: 'GCNLarge'
    model_params:
      n_hidden: 64
      p_dropout: 0.5

grid:
  min_m: 
    type: choice
    options:
      - 0.5
      - 0.55
      - 0.6
      - 0.65
  max_m:
    type: choice
    options:
      - 0.7
      - 0.8
      - 0.9
      - 0.95


pp_min_001:
  fixed:
    min_p: 0.01
    max_p: 0.01
    model_data.pretrained_name: cora_ml/GCNLarge/pp_min_0.01_pm_min_0.55

pp_min_0005:
  fixed:
    min_p: 0.005
    max_p: 0.005
    model_data.pretrained_name: cora_ml/GCNLarge/pp_min_0.005_pm_min_0.5

pp_min_0075:
  fixed:
    min_p: 0.0075
    max_p: 0.0075
    model_data.pretrained_name: cora_ml/GCNLarge/pp_min_0.0075_pm_min_0.55