seml:
  executable: /nfs/homedirs/wollschl/staff/localized_smoothing/seml/scripts/graph/cert.py
  conda_environment: localized-smoothing-cuda11
  project_root_dir: /nfs/homedirs/wollschl/staff/localized_smoothing/
  output_dir: /nfs/homedirs/wollschl/staff/localized_smoothing/experiments/slurm_out/cert

slurm:
  experiments_per_job: 1
  sbatch_options:
    gres: gpu:1       # num GPUs
    mem: 32G          # memory
    cpus-per-task: 4  # num cores
    time: 2-00:00     # max time, D-HH:MM
    partition: gpu_all

fixed:
  experiment_name: 'certify'
  certify_test: False
  dataset_name: 'cora_ml'

  budget_a: 50
  budget_d: 50
  
  n_clusters: 5
  batch_size: 25
  n_samples_eval: 100_000
  n_samples_pre_eval: 100

  clustering_type: 'metis'
  cluster_args:
    affinity: 'nearest_neighbors'

  model_data:
    name: 'APPNP'
    model_params:
      n_hidden: 64
      p_dropout: 0.5
      k_hops: 10
      alpha: 0.15

  min_p: 0.05
  min_m: 0.65
  max_m: 0.95
  max_p: 0.08

seed_0:
  fixed:
    model_data.pretrained_name: cora_ml/APPNP/pp_min_0.05_pm_min_0.65_seed_0
    seed: 0
seed_1:
  fixed:
    model_data.pretrained_name: cora_ml/APPNP/pp_min_0.05_pm_min_0.65_seed_1
    seed: 1
seed_2:
  fixed:
    model_data.pretrained_name: cora_ml/APPNP/pp_min_0.05_pm_min_0.65_seed_2
    seed: 2
seed_3:
  fixed:
    model_data.pretrained_name: cora_ml/APPNP/pp_min_0.05_pm_min_0.65_seed_3
    seed: 3
seed_4:
  fixed:
    model_data.pretrained_name: cora_ml/APPNP/pp_min_0.05_pm_min_0.65_seed_4
    seed: 4
seed_5:
  fixed:
    model_data.pretrained_name: cora_ml/APPNP/pp_min_0.05_pm_min_0.65_seed_5
    seed: 5
seed_6:
  fixed:
    model_data.pretrained_name: cora_ml/APPNP/pp_min_0.05_pm_min_0.65_seed_6
    seed: 6
seed_7:
  fixed:
    model_data.pretrained_name: cora_ml/APPNP/pp_min_0.05_pm_min_0.65_seed_7
    seed: 7
seed_8:
  fixed:
    model_data.pretrained_name: cora_ml/APPNP/pp_min_0.05_pm_min_0.65_seed_8
    seed: 8
seed_9:
  fixed:
    model_data.pretrained_name: cora_ml/APPNP/pp_min_0.05_pm_min_0.65_seed_9
    seed: 9
seed_10:
  fixed:
    model_data.pretrained_name: cora_ml/APPNP/pp_min_0.05_pm_min_0.65_seed_10
    seed: 10
seed_11:
  fixed:
    model_data.pretrained_name: cora_ml/APPNP/pp_min_0.05_pm_min_0.65_seed_11
    seed: 11
seed_12:
  fixed:
    model_data.pretrained_name: cora_ml/APPNP/pp_min_0.05_pm_min_0.65_seed_12
    seed: 12
seed_13:
  fixed:
    model_data.pretrained_name: cora_ml/APPNP/pp_min_0.05_pm_min_0.65_seed_13
    seed: 13
seed_14:
  fixed:
    model_data.pretrained_name: cora_ml/APPNP/pp_min_0.05_pm_min_0.65_seed_14
    seed: 14
seed_15:
  fixed:
    model_data.pretrained_name: cora_ml/APPNP/pp_min_0.05_pm_min_0.65_seed_15
    seed: 15
seed_16:
  fixed:
    model_data.pretrained_name: cora_ml/APPNP/pp_min_0.05_pm_min_0.65_seed_16
    seed: 16
seed_17:
  fixed:
    model_data.pretrained_name: cora_ml/APPNP/pp_min_0.05_pm_min_0.65_seed_17
    seed: 17
seed_18:
  fixed:
    model_data.pretrained_name: cora_ml/APPNP/pp_min_0.05_pm_min_0.65_seed_18
    seed: 18
seed_19:
  fixed:
    model_data.pretrained_name: cora_ml/APPNP/pp_min_0.05_pm_min_0.65_seed_19
    seed: 19