seml:
  executable: /nfs/homedirs/wollschl/staff/localized_smoothing/seml/scripts/graph/cert.py
  conda_environment: localized-smoothing-cuda11
  project_root_dir: /nfs/homedirs/wollschl/staff/localized_smoothing/
  output_dir: /nfs/homedirs/wollschl/staff/localized_smoothing/experiments/slurm_out/cert

slurm:
  experiments_per_job: 1
  sbatch_options:
    gres: gpu:1       # num GPUs
    mem: 32G          # memory
    cpus-per-task: 6  # num cores
    time: 2-00:00     # max time, D-HH:MM
    partition: gpu_all

fixed:
  experiment_name: 'certify'
  certify_test: False
  dataset_name: 'citeseer'

  budget_a: 50
  budget_d: 50
  
  n_clusters: 5
  batch_size: 10
  n_samples_eval: 100_000
  n_samples_pre_eval: 1000

  clustering_type: 'metis'
  cluster_args:
    affinity: 'nearest_neighbors'

  model_data:
    name: 'APPNP'
    model_params:
      n_hidden: 64
      p_dropout: 0.5
      k_hops: 10
      alpha: 0.15

  min_m: 0.6
  max_m: 0.6

pp_min_0:
  fixed:
    model_data.pretrained_name: citeseer/APPNP/pp_min_0.0_pm_min_0.6
  grid:
    min_p:
      type: choice
      options:
        - 0.0
    max_p:
      type: choice
      options:
        - 0.005
        - 0.01
        - 0.05
        - 0.1

pp_min_045:
  fixed:
    model_data.pretrained_name: citeseer/APPNP/pp_min_0.045_pm_min_0.6
  grid:
    min_p:
      type: choice
      options:
        - 0.035
        - 0.04
    max_p:
      type: choice
      options:
        - 0.05
        - 0.1
        - 0.15
        - 0.2

pp_min_05:
  fixed:
    model_data.pretrained_name: citeseer/APPNP/pp_min_0.05_pm_min_0.6
  grid:
    min_p:
      type: choice
      options:
        - 0.04
        - 0.045
    max_p:
      type: choice
      options:
        - 0.05
        - 0.1
        - 0.15
        - 0.2

pp_min_055:
  fixed:
    model_data.pretrained_name: citeseer/APPNP/pp_min_0.055_pm_min_0.6
  grid:
    min_p:
      type: choice
      options:
        - 0.045
        - 0.05
    max_p:
      type: choice
      options:
        - 0.1
        - 0.15
        - 0.2
        - 0.25

pp_min_06:
  fixed:
    model_data.pretrained_name: citeseer/APPNP/pp_min_0.06_pm_min_0.6
  grid:
    min_p:
      type: choice
      options:
        - 0.05
        - 0.055
    max_p:
      type: choice
      options:
        - 0.1
        - 0.15
        - 0.2
        - 0.25

pp_min_065:
  fixed:
    model_data.pretrained_name: citeseer/APPNP/pp_min_0.065_pm_min_0.6
  grid:
    min_p:
      type: choice
      options:
        - 0.055
        - 0.06
    max_p:
      type: choice
      options:
        - 0.1
        - 0.15
        - 0.2
        - 0.25

pp_min_07:
  fixed:
    model_data.pretrained_name: citeseer/APPNP/pp_min_0.07_pm_min_0.6
  grid:
    min_p:
      type: choice
      options:
        - 0.06
        - 0.065
    max_p:
      type: choice
      options:
        - 0.1
        - 0.15
        - 0.2
        - 0.25

pp_min_075:
  fixed:
    model_data.pretrained_name: citeseer/APPNP/pp_min_0.075_pm_min_0.6
  grid:
    min_p:
      type: choice
      options:
        - 0.065
        - 0.07
    max_p:
      type: choice
      options:
        - 0.1
        - 0.15
        - 0.2
        - 0.25

pp_min_08:
  fixed:
    model_data.pretrained_name: citeseer/APPNP/pp_min_0.08_pm_min_0.6
  grid:
    min_p:
      type: choice
      options:
        - 0.07
        - 0.075
    max_p:
      type: choice
      options:
        - 0.1
        - 0.15
        - 0.2
        - 0.25

pp_min_085:
  fixed:
    model_data.pretrained_name: citeseer/APPNP/pp_min_0.085_pm_min_0.6
  grid:
    min_p:
      type: choice
      options:
        - 0.075
        - 0.08
    max_p:
      type: choice
      options:
        - 0.1
        - 0.15
        - 0.2
        - 0.25

pp_min_09:
  fixed:
    model_data.pretrained_name: citeseer/APPNP/pp_min_0.09_pm_min_0.6
  grid:
    min_p:
      type: choice
      options:
        - 0.08
        - 0.085
    max_p:
      type: choice
      options:
        - 0.1
        - 0.15
        - 0.2
        - 0.25

pp_min_095:
  fixed:
    model_data.pretrained_name: citeseer/APPNP/pp_min_0.095_pm_min_0.6
  grid:
    min_p:
      type: choice
      options:
        - 0.085
        - 0.09
    max_p:
      type: choice
      options:
        - 0.1
        - 0.15
        - 0.2
        - 0.25

pp_min_1:
  fixed:
    model_data.pretrained_name: citeseer/APPNP/pp_min_0.1_pm_min_0.6
  grid:
    min_p:
      type: choice
      options:
        - 0.09
        - 0.095
    max_p:
      type: choice
      options:
        - 0.15
        - 0.2
        - 0.25
        - 0.3
